# 配置语言及相应版本
language: node_js
node_js: stable

# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules

# 配置环境
before_install:
  - npm install -g hexo-cli

install:
  - yarn install

#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate
  # - hexo deploy

after_script:
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

# after_success:
#   - cd ./public

# 项目所在分支
branches:
  only:
  - master

# 环境变量
env:
  - GH_REF=github.com/ShimingLuo/ShimingLuo.github.io.git
  - GH_TOEKN=531af457b54a88739be28be10fea318dcaa92221
  - P_BRANCH=master
  - U_EMAIL=gavinluo99@gmail.com
  - U_NAME=Gavin
