# 配置语言及相应版本
language: node_js
node_js: stable

# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules

# 配置环境
before_install:
  - npm install -g hexo-cli

install:
  - yarn install

#before_script:
 # - npm install -g gulp

script:
  # - hexo clean
  # - hexo generate
  # - hexo deploy
  - npm run deploy

after_script:
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Site updated：$(date)"
  - git push --force --quiet "https://${GH_TOKEN_GITHUB}@${GH_REF}" master:${P_BRANCH}
  - echo "GITHUB pushed"
  - git push --force --quiet "https://${GH_AUTH_GITEE}@${GH_REF_GITEE}" master:${P_BRANCH}
  - echo "GITEE pushed"

  - echo "备份MD文档文件"
  - cd ../source/_posts
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "MD backup at：$(date)"
  - git push --force --quiet "https://${GH_AUTH_GITEE}@${GH_MD_REPO}" master:${P_BRANCH}
  - echo "完成备份"
  
  - echo "开始触发更新Gitee Page服务"
  - curl -X POST --header "Content-Type: application/json;charset=UTF-8" "https://gitee.com/api/v5/repos/gitfuck99/blog/pages/builds" -d '{"access_token":"1a56178e8749d9bb607202a93350dc04"}'


# 项目所在分支
branches:
  only:
  - master

# 环境变量
env:
  global:
    # github
    - GH_REF: github.com/ShimingLuo/ShimingLuo.github.io.git
    - GH_TOKEN: f98e8fff0cde9adfe1bb585d6eae4b7a6706f179
    - GH_TOKEN_GITHUB: shimingluo:19931225luo..
    # gitee
    - GH_REF_GITEE: gitee.com/gitfuck99/blog.git
    - GH_AUTH_GITEE: gitfuck99:19931225luo..
    # MD文档的GIT repo
    - GH_MD_REPO: gitee.com/gitfuck99/articles.git
    # 分支
    - P_BRANCH: master
    - U_EMAIL: gavinluo99@gmail.com
    - U_NAME: Gavin
